['Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmp4zcc6tii/solution_0.py", line 37, in <module>\n    print(Solution().countCompleteDayPairs(hours = [12,12,30,24,24]))\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmp4zcc6tii/solution_0.py", line 31, in countCompleteDayPairs\n    temp_hour = hours[index] % mu\nIndexError: list index out of range\n', 'Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmp4zcc6tii/solution_1.py", line 37, in <module>\n    print(Solution().countCompleteDayPairs(hours = [72,48,24,3]))\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmp4zcc6tii/solution_1.py", line 31, in countCompleteDayPairs\n    temp_hour = hours[index] % mu\nIndexError: list index out of range\n']