['Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmp3ia2w8d7/solution_2.py", line 84, in <module>\n    print(Solution().countOfPairs(nums = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]))\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmp3ia2w8d7/solution_2.py", line 61, in countOfPairs\n    hold_old = cache[idx_outer][idx_mid][idx_mid_cmpl]\nIndexError: list index out of range\n', 'Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmp3ia2w8d7/solution_6.py", line 84, in <module>\n    print(Solution().countOfPairs(nums = [10, 5, 15, 10, 20]))\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmp3ia2w8d7/solution_6.py", line 61, in countOfPairs\n    hold_old = cache[idx_outer][idx_mid][idx_mid_cmpl]\nIndexError: list index out of range\n']