['Outputs do not match', 'Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpyy7f4ccd/solution_3.py", line 69, in <module>\n    print(Solution().maximumEnergy(energy = [5, 5, 5, 5, 5, 5, 5, 5, 5, 5], k = 1))\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpyy7f4ccd/solution_3.py", line 66, in maximumEnergy\n    final_result = process_index(length_energy - 2, dynamic_array, indices_deque, peak_energy)\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpyy7f4ccd/solution_3.py", line 50, in process_index\n    reference_index = front_value(indices_state)\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpyy7f4ccd/solution_3.py", line 29, in front_value\n    return dq[0]\nIndexError: list index out of range\n']