['Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmppvtsu4mg/solution_0.py", line 58, in <module>\n    print(Solution().maxPointsInsideSquare(points = [[10,10],[-10,-10],[10,-10],[-10,10]], s = "abcd"))\nTypeError: maxPointsInsideSquare() got an unexpected keyword argument \'points\'\n', 'Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmppvtsu4mg/solution_1.py", line 58, in <module>\n    print(Solution().maxPointsInsideSquare(points = [[0,0],[1,1],[-1,-1],[2,2],[-2,-2]], s = "abcde"))\nTypeError: maxPointsInsideSquare() got an unexpected keyword argument \'points\'\n']