['Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmp8cqqs9lm/solution_0.py", line 43, in <module>\n    print(Solution().maximumLength(nums = [1,2,3,4]))\nTypeError: maximumLength() got an unexpected keyword argument \'nums\'\n', 'Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmp8cqqs9lm/solution_1.py", line 43, in <module>\n    print(Solution().maximumLength(nums = [1,2,1,1,2,1,2]))\nTypeError: maximumLength() got an unexpected keyword argument \'nums\'\n']