['Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpgw8r910h/solution_0.py", line 66, in <module>\n    print(Solution().findPermutation(nums = [0,3,1,2]))\nTypeError: findPermutation() got an unexpected keyword argument \'nums\'\n', 'Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpgw8r910h/solution_1.py", line 66, in <module>\n    print(Solution().findPermutation(nums = [0,2,1]))\nTypeError: findPermutation() got an unexpected keyword argument \'nums\'\n']