['Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpzl3_f7h7/solution_0.py", line 67, in <module>\n    print(Solution().queryResults(limit = 5, queries = [[0,10],[1,20],[2,10],[3,30],[4,40],[5,50]]))\nTypeError: queryResults() got an unexpected keyword argument \'limit\'\n', 'Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpzl3_f7h7/solution_1.py", line 67, in <module>\n    print(Solution().queryResults(limit = 4, queries = [[1,4],[2,5],[1,3],[3,4]]))\nTypeError: queryResults() got an unexpected keyword argument \'limit\'\n']