['Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpssqexrnn/solution_0.py", line 57, in <module>\n    print(Solution().maximumTotalCost(nums = [5,-3,2,7,-8,9]))\nTypeError: maximumTotalCost() got an unexpected keyword argument \'nums\'\n', 'Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpssqexrnn/solution_1.py", line 57, in <module>\n    print(Solution().maximumTotalCost(nums = [1000000000, -1000000000, 1000000000, -1000000000]))\nTypeError: maximumTotalCost() got an unexpected keyword argument \'nums\'\n']