['Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpeh72x1xc/solution_12.py", line 34, in <module>\n    print(Solution().valueAfterKSeconds(n = 2000, k = 1000))\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpeh72x1xc/solution_12.py", line 32, in valueAfterKSeconds\n    REPEAT_Update(0)\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpeh72x1xc/solution_12.py", line 31, in REPEAT_Update\n    REPEAT_Update(counter + 1)\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpeh72x1xc/solution_12.py", line 31, in REPEAT_Update\n    REPEAT_Update(counter + 1)\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpeh72x1xc/solution_12.py", line 31, in REPEAT_Update\n    REPEAT_Update(counter + 1)\n  [Previous line repeated 994 more times]\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpeh72x1xc/solution_12.py", line 24, in REPEAT_Update\n    if counter >= k:\nRecursionError: maximum recursion depth exceeded in comparison\n']