['Outputs do not match', 'Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpn5wm6atw/solution_3.py", line 87, in <module>\n    print(Solution().maximumEnergy(energy = [5, 5, 5, 5, 5, 5, 5, 5, 5, 5], k = 1))\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpn5wm6atw/solution_3.py", line 84, in maximumEnergy\n    loop_descend(len_x - 2, 0, process_index, dp_list, energy, k, queue_deque)\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpn5wm6atw/solution_3.py", line 81, in loop_descend\n    act(start, dp_list_ref, energy_ref, k_val, deque_ref)\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpn5wm6atw/solution_3.py", line 67, in process_index\n    dp_ref[i] = enrg_ref[i] + dp_ref[front(dq)]\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpn5wm6atw/solution_3.py", line 33, in front\n    return dq[0]\nIndexError: list index out of range\n']