['Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpfpz0070x/solution_0.py", line 76, in <module>\n    print(Solution().maximumSumSubsequence(nums = [3,5,9], queries = [[1,-2],[0,-3]]))\nTypeError: maximumSumSubsequence() got an unexpected keyword argument \'nums\'\n', 'Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpfpz0070x/solution_1.py", line 76, in <module>\n    print(Solution().maximumSumSubsequence(nums = [0,-1], queries = [[0,-5]]))\nTypeError: maximumSumSubsequence() got an unexpected keyword argument \'nums\'\n']