['Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpz_lr33wb/solution_0.py", line 54, in <module>\n    print(Solution().shortestDistanceAfterQueries(n = 5, queries = [[2, 4], [0, 2], [0, 4]]))\nTypeError: shortestDistanceAfterQueries() got an unexpected keyword argument \'n\'\n', 'Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpz_lr33wb/solution_1.py", line 54, in <module>\n    print(Solution().shortestDistanceAfterQueries(n = 4, queries = [[0, 3], [0, 2]]))\nTypeError: shortestDistanceAfterQueries() got an unexpected keyword argument \'n\'\n']