['Outputs do not match', 'Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpn8vyc6ih/solution_3.py", line 51, in <module>\n    print(Solution().maximumEnergy(energy = [5, 5, 5, 5, 5, 5, 5, 5, 5, 5], k = 1))\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpn8vyc6ih/solution_3.py", line 37, in maximumEnergy\n    val2 = f[q[0]]\nIndexError: deque index out of range\n']