['Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmp_w9vr4vb/solution_0.py", line 43, in <module>\n    print(Solution().countCompleteDayPairs(hours = [12,12,30,24,24]))\nTypeError: countCompleteDayPairs() got an unexpected keyword argument \'hours\'\n', 'Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmp_w9vr4vb/solution_1.py", line 43, in <module>\n    print(Solution().countCompleteDayPairs(hours = [72,48,24,3]))\nTypeError: countCompleteDayPairs() got an unexpected keyword argument \'hours\'\n']