['Outputs do not match', 'Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpw1kp1dpe/solution_3.py", line 38, in <module>\n    print(Solution().maximumEnergy(energy = [5, 5, 5, 5, 5, 5, 5, 5, 5, 5], k = 1))\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpw1kp1dpe/solution_3.py", line 30, in maximumEnergy\n    dp[idx] = energy[idx] + dp[que[0]]\nIndexError: list index out of range\n']